BASE_URL: http://localhost:8080
STUDENT_SERVICE_BASE_URL: http://localhost:8081
SWAGGER_APPLICATION_BASE_URL: http://localhost:8082
PAYMENT_SERVICE_BASE_URL: http://localhost:8083
OPENAI_SERVICE_BASE_URL: http://localhost:8084

server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true

  cloud:
    gateway:
      routes:
        - id: student-service
          predicates:
            - Path=/students/**
          uri: ${STUDENT_SERVICE_BASE_URL}
          filters:
            - StripPrefix=2
        - id: swagger-application
          predicates:
            - Path=/api/**
          uri: ${SWAGGER_APPLICATION_BASE_URL}
          filters:
            - StripPrefix=2
        - id: payment-service
          predicates:
            - Path=/payments/**
          uri: ${PAYMENT_SERVICE_BASE_URL}
          filters:
            - StripPrefix=2
        - id: validate
          predicates:
            - Path=/validate/**
          uri: ${STUDENT_SERVICE_BASE_URL}
          filters:
            - StripPrefix=2
        - id: openai-service
          predicates:
            - Path=/openai/**
          uri: ${OPENAI_SERVICE_BASE_URL}
          filters:
            - StripPrefix=2
        - id: role # TODO This can be removed it's just a PrefixPath example.
          predicates:
            - Path=/role/**
          uri: ${STUDENT_SERVICE_BASE_URL}
          filters:
            - StripPrefix=2
            - PrefixPath=/students
  main:
    web-application-type: reactive

google:
  recaptcha:
    url: https://www.google.com/recaptcha/api/siteverify
    key:
      site:  # SITE KEY
      secret:  # SECRET KEY
      threshold: 0.5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
