BASE_URL: http://localhost:8080
STUDENT_SERVICE_BASE_URL: http://localhost:8081
SWAGGER2_APPLICATION_BASE_URL: http://localhost:8082
PAYMENT_SERVICE_BASE_URL: http://localhost:8083

zuul:
  prefix: /gateway
  routes:
    student-service:
      path: /students/**
      url: ${STUDENT_SERVICE_BASE_URL}
      sensitive-headers:
      strip-prefix: false
      serviceId: student-service
    swagger2-application:
      path: /api/**
      url: ${SWAGGER2_APPLICATION_BASE_URL}
      sensitive-headers:
      strip-prefix: false
      serviceId: swagger2-application
    payment-service:
      path: /payments/**
      url: ${PAYMENT_SERVICE_BASE_URL}
      sensitive-headers:
      strip-prefix: false
      serviceId: payment-service
    validate:
      path: /validate/**
      url: ${STUDENT_SERVICE_BASE_URL}
      sensitive-headers:
      strip-prefix: false
      serviceId: validate

ribbon:
  eureka:
    enabled: false

server:
  port: 8080

swagger:
  documentation:
    services:
      - name: student-service
        url: /gateway/students/v2/api-docs
        version: 2.0
      - name: swagger2-application
        url: /gateway/api/v2/api-docs
        version: 2.0

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

google:
  recaptcha:
    url: https://www.google.com/recaptcha/api/siteverify
    key:
      site:  # SITE KEY
      secret:  # SECRET KEY
      threshold: 0.5
