BASE_URL: http://localhost:8080
STUDENT_SERVICE_BASE_URL: lb://student-service
SWAGGER_APPLICATION_BASE_URL: lb://swagger-application
PAYMENT_SERVICE_BASE_URL: lb://payment-service
OPENAI_SERVICE_BASE_URL: lb://openai-service

server:
  port: 8080

spring:
  application:
    name: api-gateway

  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true

  cloud:
    gateway:
      routes:
        - id: student-service
          predicates:
            - Path=/students/**
          uri: ${STUDENT_SERVICE_BASE_URL}
        - id: swagger-application
          predicates:
            - Path=/api/**
          uri: ${SWAGGER_APPLICATION_BASE_URL}
        - id: payment-service
          predicates:
            - Path=/payments/**
          uri: ${PAYMENT_SERVICE_BASE_URL}
        - id: validate
          predicates:
            - Path=/validate/**
          uri: ${STUDENT_SERVICE_BASE_URL}
        - id: openai-service
          predicates:
            - Path=/openai/**
          uri: ${OPENAI_SERVICE_BASE_URL}
        - id: role # TODO This can be removed it's just a PrefixPath example.
          predicates:
            - Path=/role/**
          uri: ${STUDENT_SERVICE_BASE_URL}
            - PrefixPath=/students
  main:
    web-application-type: reactive

  docker:
    compose:
      enabled: false

  config:
    import: optional:file:.env[.properties]

google:
  recaptcha:
    url: https://www.google.com/recaptcha/api/siteverify
    key:
      site: ${SITE_KEY} # SITE KEY
      secret: ${SECRET_KEY} # SECRET KEY
      threshold: 0.5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html # http://localhost:8080/swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /openai/api-docs
        name: OpenAI Service
        uri: ${OPENAI_SERVICE_BASE_URL}
      - url: /payment/api-docs
        name: Payment Service
        uri: ${PAYMENT_SERVICE_BASE_URL}
      - url: /student/api-docs
        name: Student Service
        uri: ${STUDENT_SERVICE_BASE_URL}
      - url: /swagger/api-docs
        name: Swagger Service
        uri: ${SWAGGER_APPLICATION_BASE_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}
