spring:
  application:
    name: gitlab-service

  config:
    import: optional:file:.env[.properties]

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8086

feign:
  services:
    gitlab-client:
      url: ${GITLAB_API_URL:https://gitlab.com/api/v4}
      private-token: ${GITLAB_PRIVATE_TOKEN:gitlab-private-token}
      path-with-namespace: ${GITLAB_URL_PATH_WITH_NAMESPACE:}
      max-number-of-project: 100

springdoc:
  api-docs:
    path: /gitlab/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, prometheus
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_METRICS_URL:http://localhost:4318/v1/metrics}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACES_URL:http://localhost:4318/v1/traces}
    logging:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_LOGS_URL:http://localhost:4318/v1/logs}
