GATEWAY_BASE_URL: ${GATEWAY_BASE_URL_ENV:http://localhost:8080}
KEYCLOAK_BASE_URL: http://localhost:9090
PAYMENT_SERVICE_REALM: payment-service

spring:
  application:
    name: payment-service

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=payment_schema
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: payment_schema
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    schemas: payment_schema
    table: schema_version
    validate-on-migrate: false
    locations: ${DB_MIGRATION_LOCATIONS:classpath:db/migration/common,classpath:db/migration/non-prod}

  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_BASE_URL}/realms/${PAYMENT_SERVICE_REALM}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: payment-service
      principle-attribute: payment-service

server:
  port: 8083

springdoc:
  api-docs:
    path: /payment/api-docs
  swagger-ui:
    path: /swagger-ui.html # http://localhost:8083/swagger-ui/index.html
    csrf:
      enabled: true

  security: # Custom variables
    config:
      password-flow: true
      openid-discovery: false
      auth-code-flow: false
      implicit-flow: false
      bearer: false