spring:
  datasource:
    url: jdbc:tc:postgresql:16:///postgres?currentSchema=stock_exchange_service
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    table: schema_version
    validate-on-migrate: false

stock-exchange:
  minimum-number-of-stocks: 5
