-- Switch to the pluggable database and set schema
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = MB_ORACLE_USER;

-- Create table (Oracle doesn't support CREATE TABLE IF NOT EXISTS, using PL/SQL block instead)
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE MB_ORACLE_USER.CUSTOMERS
        (id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, first_name VARCHAR2(255), last_name VARCHAR2(255), email VARCHAR2(255))';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -00955 THEN -- table already exists
            RAISE;
        END IF;
END;
/

-- Oracle doesn't have REPLICA IDENTITY, this is PostgreSQL specific
-- For Oracle change data capture, you would typically use Oracle GoldenGate or LogMiner

-- Insert sample data
INSERT INTO MB_ORACLE_USER.CUSTOMERS (first_name, last_name, email)
VALUES ('Sally', 'Thomas', 'sally.thomas@acme.com');

INSERT INTO MB_ORACLE_USER.CUSTOMERS (first_name, last_name, email)
VALUES ('George', 'Bailey', 'gbailey@foobar.com');

INSERT INTO MB_ORACLE_USER.CUSTOMERS (first_name, last_name, email)
VALUES ('Edward', 'Walker', 'ed@walker.com');

INSERT INTO MB_ORACLE_USER.CUSTOMERS (first_name, last_name, email)
VALUES ('Anne', 'Kretchmar', 'annek@noanswer.org');

-- Commit the inserts
COMMIT;

-- Update and delete operations
UPDATE MB_ORACLE_USER.CUSTOMERS
SET email = 'sally.thomas.updated@acme.commmm'
WHERE first_name = 'Sally';

DELETE
FROM MB_ORACLE_USER.CUSTOMERS
WHERE first_name = 'George';

-- Commit the changes
COMMIT;
