CREATE SCHEMA IF NOT EXISTS config_server_schema;

CREATE TABLE IF NOT EXISTS config_server_schema.properties
(
    ID          INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    CREATED_ON  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    APPLICATION VARCHAR(255),
    PROFILE     VARCHAR(255),
    LABEL       VARCHAR(255),
    PROP_KEY    VARCHAR(255),
    PROP_VALUE  VARCHAR(255),
    PRIMARY KEY (ID)
);

INSERT INTO config_server_schema.properties (APPLICATION, PROFILE, LABEL, PROP_KEY, PROP_VALUE)
VALUES ('swagger-application', 'development', 'main', 'service.name', 'swagger-application-dev'),
       ('swagger-application', 'production', 'main', 'service.name', 'swagger-application-prod'),
       ('swagger-application', 'development', 'main', 'service.first-url', 'https://client-first-url-dev.com'),
       ('swagger-application', 'development', 'main', 'service.second-url', 'https://client-second-url-dev.com'),
       ('swagger-application', 'production', 'main', 'service.first-url', 'https://client-first-url-prod.com'),
       ('swagger-application', 'development', 'main', 'service.first-url', 'https://second-client-dev.com'),
       ('swagger-application', 'production', 'main', 'service.first-url', 'https://second-client-prod.com'),
       ('test-app', 'default', 'main', 'app.feature.enabled', 'true'),
       ('test-app', 'default', 'main', 'app.timeout', '30'),
       ('test-app', 'default', 'main', 'app.message', 'hello from config'),
       ('other-app', 'default', 'main', 'other.setting', 'other-value');
