-- Create and populate our products using a single insert with many rows
CREATE TABLE debezium.products
(
    id          NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 101) NOT NULL PRIMARY KEY,
    name        VARCHAR2(255)                                                       NOT NULL,
    description VARCHAR2(512),
    weight      FLOAT
);
GRANT SELECT ON debezium.products to c##dbzuser;
ALTER TABLE debezium.products
    ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO debezium.products
VALUES (NULL, 'scooter', 'Small 2-wheel scooter', 3.14);
INSERT INTO debezium.products
VALUES (NULL, 'car battery', '12V car battery', 8.1);
INSERT INTO debezium.products
VALUES (NULL, '12-pack drill bits', '12-pack of drill bits with sizes ranging from #40 to #3', 0.8);
INSERT INTO debezium.products
VALUES (NULL, 'hammer', '12oz carpenter''s hammer', 0.75);
INSERT INTO debezium.products
VALUES (NULL, 'hammer', '14oz carpenter''s hammer', 0.875);
INSERT INTO debezium.products
VALUES (NULL, 'hammer', '16oz carpenter''s hammer', 1.0);
INSERT INTO debezium.products
VALUES (NULL, 'rocks', 'box of assorted rocks', 5.3);
INSERT INTO debezium.products
VALUES (NULL, 'jacket', 'water resistent black wind breaker', 0.1);
INSERT INTO debezium.products
VALUES (NULL, 'spare tire', '24 inch spare tire', 22.2);

-- Create and populate the products on hand using multiple inserts
CREATE TABLE debezium.products_on_hand
(
    product_id NUMBER(4) NOT NULL PRIMARY KEY,
    quantity   NUMBER(4) NOT NULL,
    FOREIGN KEY (product_id) REFERENCES products (id)
);
GRANT SELECT ON debezium.products_on_hand to c##dbzuser;
ALTER TABLE debezium.products_on_hand
    ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO debezium.products_on_hand
VALUES (101, 3);
INSERT INTO debezium.products_on_hand
VALUES (102, 8);
INSERT INTO debezium.products_on_hand
VALUES (103, 18);
INSERT INTO debezium.products_on_hand
VALUES (104, 4);
INSERT INTO debezium.products_on_hand
VALUES (105, 5);
INSERT INTO debezium.products_on_hand
VALUES (106, 0);
INSERT INTO debezium.products_on_hand
VALUES (107, 44);
INSERT INTO debezium.products_on_hand
VALUES (108, 2);
INSERT INTO debezium.products_on_hand
VALUES (109, 5);

-- Create some customers ...
CREATE TABLE debezium.customers
(
    id         NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1001) NOT NULL PRIMARY KEY,
    first_name VARCHAR2(255)                                                        NOT NULL,
    last_name  VARCHAR2(255)                                                        NOT NULL,
    email      VARCHAR2(255)                                                        NOT NULL UNIQUE
);
GRANT SELECT ON debezium.customers to c##dbzuser;
ALTER TABLE debezium.customers
    ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO debezium.customers
VALUES (NULL, 'Sally', 'Thomas', 'sally.thomas@acme.com');
INSERT INTO debezium.customers
VALUES (NULL, 'George', 'Bailey', 'gbailey@foobar.com');
INSERT INTO debezium.customers
VALUES (NULL, 'Edward', 'Walker', 'ed@walker.com');
INSERT INTO debezium.customers
VALUES (NULL, 'Anne', 'Kretchmar', 'annek@noanswer.org');

-- Create some very simple orders
CREATE TABLE debezium.orders
(
    id         NUMBER(6) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 10001) NOT NULL PRIMARY KEY,
    order_date DATE                                                                  NOT NULL,
    purchaser  NUMBER(4)                                                             NOT NULL,
    quantity   NUMBER(4)                                                             NOT NULL,
    product_id NUMBER(4)                                                             NOT NULL,
    FOREIGN KEY (purchaser) REFERENCES customers (id),
    FOREIGN KEY (product_id) REFERENCES products (id)
);
GRANT SELECT ON debezium.orders to c##dbzuser;
ALTER TABLE debezium.orders
    ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

INSERT INTO debezium.orders
VALUES (NULL, '16-JAN-2016', 1001, 1, 102);
INSERT INTO debezium.orders
VALUES (NULL, '17-JAN-2016', 1002, 2, 105);
INSERT INTO debezium.orders
VALUES (NULL, '19-FEB-2016', 1002, 2, 106);
INSERT INTO debezium.orders
VALUES (NULL, '21-FEB-2016', 1003, 1, 107);
